server:
  port: 8080
  servlet:
    # 配置访问路径，一定要加 /
    context-path: /prisonbreak

spring:
    application:
      # 服务名
      name: prisonbreak
    ### 数据源配置
    datasource:
      # 使用druid连接池
      type: com.alibaba.druid.pool.DruidDataSource
      # oracle
      # oracle.jdbc.driver.OracleDriver is deprecated.Having use oracle.jdbc.OracleDriver.
#      driver-class-name: oracle.jdbc.OracleDriver
#      url: jdbc:oracle:thin:@192.168.2.220:1521/lcba.net
#      username: tyyw2_lcba
#      password: tyyw2_lcba

      # mysql
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://localhost:3306/prison_break?allowMultiQueries=true&useUnicode=true&characterEncoding=UTF-8&serverTimezone=GMT
      username: root
      password: 123456

      ### 数据源的其他配置
      # 配置初始化大小、最小、最大
      initialSize: 5
      minIdle: 5
      maxActive: 20
      # 获取连接等待超时时间
      maxWait: 60000
      # 间隔多久进行一次检测，检测需要关闭的空闲连接
      timeBetweenEvictionRunsMillis: 60000
      # 一个连接在池中最小生存的时间，单位是毫秒
      minEvictableIdleTimeMillis: 300000
      # 校验SQL，Oracle配置 spring.datasource.validationQuery: SELECT 1 FROM DUAL，
      # 如果不配validationQuery项，则下面三项配置无用
      validationQuery: SELECT 1 FROM DUAL
      testWhileIdle: true
      testOnBorrow: false
      testOnReturn: false
      # 打开PSCache，并指定每个连接上PSCache的大小。oracle设为true，mysql设为false。分库分表较多推荐设置为false
      poolPreparedStatements: true
      maxPoolPreparedStatementPerConnectionSize: 20
      ### 配置监控统计拦截的filters，去掉后监控界面sql无法统计，'wall'用于防火墙,
      # 如果使用log4j，则filters: stat,wall,log4j
      filters: stat,wall
      # 合并多个DruidDataSource的监控数据
      useGlobalDataSourceStat: true
      # 通过connectionProperties属性来打开mergeSql功能：慢SQL记录
      connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=500

# 配置mybatis-plus
mybatis-plus:
  # 配置扫描xml
  mapper-locations: classpath:/mapper/*Mapper.xml
  # 是否开启动态加载  默认:false,3.1.0版本以上已经移除
#  enabled: true
  # 通用枚举，支持统配符 * 或者 ; 分割
#  typeEnumsPackage: com.xwl.prisonbreak.model.enums
  # 实体扫描，多个package用逗号或者分号分隔
  type-aliases-package: com.xwl.prisonbreak.model.po
  global-config:
    # 刷新mapper
#    refresh: true
    # MyBatis-Plus 全局策略中的 DB 策略配置
    db-config:
      #全局默认主键类型  0:"数据库ID自增", 1:"用户输入ID",2:"全局唯一ID (数字类型唯一ID)", 3:"全局唯一ID UUID";
      # 如果是oracle数据库则 id-type: INPUT
      id-type: AUTO
      #字段策略 0:"忽略判断",1:"非 NULL 判断"),2:"非空判断"
      field-strategy: not_empty
      #驼峰下划线转换
      column-underline: true
      #数据库大写下划线转换
#      capital-mode: true
      # 逻辑删除配置
      # 逻辑已删除值,(逻辑删除下有效),默认值1
      logic-delete-value: 1
      # 逻辑未删除值,(逻辑删除下有效)，默认值0
      logic-not-delete-value: 0
      # 全局配置表前缀：如 tbl_，如果所有的表前缀都一致，建议开启此配置，在每个实体类中就无效再使用@TableName(value = "")注解，
      # 如果不一致则不要启用此配置
#      table-prefix: tbl_
      # 刷新mapper
#      refresh-mapper: true

  configuration:
    # 是否开启自动驼峰命名规则（camel case）映射，即从经典数据库列名 A_COLUMN（下划线命名） 到经典 Java 属性名 aColumn（驼峰命名） 的类似映射。
    # 默认值为true
    map-underscore-to-camel-case: true
    # 全局地开启或关闭配置文件中的所有映射器已经配置的任何缓存，默认为 true。
    cache-enabled: false
    # 控制台打印sql语句
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    # MyBatis 自动映射时未知列或未知属性处理策略，通过该配置可指定 MyBatis 在自动映射过程中遇到未知列或者未知属性时如何处理，总共有 3 种可选值：
    # NONE：不做任何处理 (默认值)
    # WARNING：以日志的形式打印相关警告信息
    # FAILING：当作映射失败处理，并抛出异常和详细信息
    auto-mapping-unknown-column-behavior: failing

# ==================== 日志使用（logback）  ============================
logging:
  config: classpath:logback-spring.xml
  level:
    com.xwl.prisonbreak: debug